version: '3.8'
services:
  telegram-uploader:
    build: .
    container_name: telegram-uploader
    env_file:
      - .env
    volumes:
      - "/media/gylang/My Book/Backup/telegram_uploader.py/media:/media:ro"

